export const postsActionTypes = {
	ADD_POSTS: "ADD_POSTS",
	UPDATE_POST: "UPDATE_POST",
	ADD_POST: "ADD_POST",
	DELETE_POST: "DELETE_POST",
	ADD_COMMENT: "ADD_COMMENT",
	ADD_COMMENTS: "ADD_COMMENTS",
	UPDATE_COMMENT: "UPDATE_COMMENT",
};
